### ISSUE TITLE
Exemplo demonstrativo apresenta erros

### ISSUE THREAD

**Issue by thenicolau** [DesignLiquido/liquido#20]
o exemplo demonstrativo com o 
```bash
npm i liquido
```
apresenta erros como não ter a biblioteca @designliquido/lincones-sqlite e também não tem o arquivo .ambiente 

Possíveis correções:

- [x] Adicionar  @designliquido/lincones-sqlite  em dependencias ou remover como algo obrigatório ao iniciar uma rota
- [x] Adicionar o .ambiente ou remover como algo obrigatório ao iniciar o sistema

**Comment by leonelsanchesdasilva** [comment]
A existência de `.ambiente` já foi corrigida na versão 0.0.8 do pacote.

**Comment by leonelsanchesdasilva** [comment]
` @designliquido/lincones-sqlite` agora é dependência transitiva, também corrigido na versão 0.0.8.
