### ISSUE TITLE
Erro em tempo de execucao 

### ISSUE THREAD

**Issue by thenicolau** [DesignLiquido/liquido#21]
Localmente pela própria biblioteca, o comando
```bash
yarn iniciar
```
apresenta diversos erros

**Comment by leonelsanchesdasilva** [comment]
@thenicolau O que seria `yarn iniciar`? Quais são os erros?

**Comment by samuelrvg** [comment]
Encerrando ISSUE, @thenicolau se ver necessidade, pode reabrir a ISSUE com mais informações.
